export function DocumentFooter({ model }) {
  return (
    <footer className="document-footer">
      <p>{model.privacyNotice}</p>
      <div className="mt-2 flex flex-wrap justify-between gap-2">
        <span>Generated by ALAGA-SYS</span>
        <time dateTime={model.generatedAt}>{model.generatedLabel}</time>
      </div>
    </footer>
  );
}
