export const ROUTES = Object.freeze({
  login: "/login",
  dashboard: "/",
  households: "/households",
  residents: "/residents",
  appointments: "/appointments",
  appointmentCalendar: "/appointments/calendar",
  appointmentQueue: "/appointments/queue",
  healthRecords: "/health-records",
  healthRecordDetail: (encounterId) => `/health-records/${encounterId}`,
  maternalChildCare: "/maternal-child-care",
  medicineInventory: "/medicine-inventory",
  announcements: "/announcements",
  notifications: "/notifications",
  activity: "/activity",
  healthCenter: "/health-center",
  faq: "/faq",
  contact: "/contact",
  reports: "/reports",
  auditLogs: "/audit-logs",
  userManagement: "/user-management",
  settings: "/settings",
  account: "/account",
  accessDenied: "/access-denied",
  configurationError: "/configuration-error",
});
