export const ROUTES = Object.freeze({
  login: "/login",
  dashboard: "/",
  households: "/households",
  residents: "/residents",
  appointments: "/appointments",
  healthRecords: "/health-records",
  maternalChildCare: "/maternal-child-care",
  medicineInventory: "/medicine-inventory",
  announcements: "/announcements",
  reports: "/reports",
  auditLogs: "/audit-logs",
  userManagement: "/user-management",
  settings: "/settings",
  account: "/account",
  accessDenied: "/access-denied",
  configurationError: "/configuration-error",
});
