import { ArrowDownAZ, Eye, Home, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

import { PageHeading } from "@/components/common/PageHeading";
import { EmptyState, ErrorState } from "@/components/common/StateDisplay";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/features/auth/authContext";
import { hasPermission, PERMISSIONS } from "@/features/auth/permissions";
import {
  HOUSEHOLD_SORTS,
  HOUSEHOLD_STATUS_LABELS,
  initialHouseholdFilters,
} from "@/features/registry/constants";
import { HouseholdDetailDialog } from "@/features/registry/HouseholdDetailDialog";
import { HouseholdFormDialog } from "@/features/registry/HouseholdFormDialog";
import {
  useDeploymentContext,
  useHouseholds,
  usePuroks,
  useRegistryMutation,
} from "@/features/registry/hooks";
import { DeploymentBarangayContext } from "@/features/registry/DeploymentBarangayContext";
import { RegistryActionDialog } from "@/features/registry/RegistryActionDialog";
import { RegistryPagination } from "@/features/registry/RegistryPagination";
import { RegistrySkeleton } from "@/features/registry/RegistrySkeleton";
import { useDebouncedValue } from "@/features/registry/useDebouncedValue";
import { registryService } from "@/services/registryService";

export default function HouseholdRegistryPage() {
  const { profile } = useAuth();
  const canManage = hasPermission(profile.role, PERMISSIONS.MANAGE_HOUSEHOLDS);
  const canRestore = hasPermission(
    profile.role,
    PERMISSIONS.RESTORE_ARCHIVED_REGISTRY,
  );
  const [filters, setFilters] = useState({ ...initialHouseholdFilters });
  const [search, setSearch] = useState("");
  const debouncedSearch = useDebouncedValue(search.trim(), 350);
  const effectiveFilters = useMemo(
    () => ({ ...filters, search: debouncedSearch }),
    [debouncedSearch, filters],
  );
  const query = useHouseholds(effectiveFilters);
  const deploymentContext = useDeploymentContext();
  const puroks = usePuroks();
  const [form, setForm] = useState({ open: false, record: null });
  const [detailId, setDetailId] = useState(null);
  const [action, setAction] = useState({ record: null, restoring: false });
  const statusMutation = useRegistryMutation(({ id, status }) =>
    registryService.setHouseholdStatus(id, status),
  );

  function update(next) {
    setFilters((current) => ({ ...current, ...next }));
  }

  function clearFilters() {
    setSearch("");
    setFilters({ ...initialHouseholdFilters });
  }

  async function confirmStatus() {
    try {
      await statusMutation.mutateAsync({
        id: action.record.id,
        status: action.restoring ? "active" : "archived",
      });
      toast.success(
        action.restoring ? "Household restored" : "Household archived",
      );
      setAction({ record: null, restoring: false });
      setDetailId(null);
    } catch {
      // The reusable confirmation dialog renders the mapped service error.
    }
  }

  const items = query.data?.items ?? [];
  const hasFilters = Boolean(
    debouncedSearch ||
    filters.purok_id ||
    filters.status ||
    filters.include_archived,
  );

  return (
    <div className="space-y-6">
      <PageHeading
        eyebrow="Registry"
        title="Households"
        description="Manage locality-validated household records, heads, and resident membership. Household numbers are generated by the database."
        actions={
          canManage ? (
            <Button
              onClick={() => setForm({ open: true, record: null })}
              disabled={
                deploymentContext.isLoading || deploymentContext.isError
              }
            >
              <Plus /> Add household
            </Button>
          ) : null
        }
      />
      <DeploymentBarangayContext query={deploymentContext} compact />

      <Card>
        <CardContent className="space-y-4 p-4 sm:p-6">
          <div className="grid gap-3 lg:grid-cols-3">
            <div className="relative lg:col-span-2">
              <Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
              <Input
                value={search}
                onChange={(event) => {
                  setSearch(event.target.value);
                  update({ page: 1 });
                }}
                placeholder="Search number, head, or address"
                aria-label="Search households"
                className="pl-9"
              />
            </div>
            <select
              value={filters.purok_id}
              onChange={(event) =>
                update({ purok_id: event.target.value, page: 1 })
              }
              disabled={puroks.isLoading || deploymentContext.isError}
              className="h-10 rounded-lg border border-input bg-background px-3 text-sm disabled:opacity-50"
              aria-label="Filter households by purok"
            >
              <option value="">All puroks</option>
              {(puroks.data ?? []).map((purok) => (
                <option key={purok.id} value={purok.id}>
                  {purok.name}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-wrap gap-3">
            <select
              value={filters.status}
              onChange={(event) =>
                update({ status: event.target.value, page: 1 })
              }
              className="h-10 rounded-lg border border-input bg-background px-3 text-sm"
              aria-label="Filter households by status"
            >
              <option value="">Current statuses</option>
              {Object.entries(HOUSEHOLD_STATUS_LABELS).map(([value, label]) => (
                <option key={value} value={value}>
                  {label}
                </option>
              ))}
            </select>
            <select
              value={filters.sort}
              onChange={(event) =>
                update({ sort: event.target.value, page: 1 })
              }
              className="h-10 rounded-lg border border-input bg-background px-3 text-sm"
              aria-label="Sort households"
            >
              {Object.entries(HOUSEHOLD_SORTS).map(([value, label]) => (
                <option key={value} value={value}>
                  Sort: {label}
                </option>
              ))}
            </select>
            <Button
              type="button"
              variant="outline"
              onClick={() =>
                update({
                  direction: filters.direction === "asc" ? "desc" : "asc",
                })
              }
            >
              <ArrowDownAZ />{" "}
              {filters.direction === "asc" ? "Ascending" : "Descending"}
            </Button>
            {canRestore ? (
              <label className="flex h-10 items-center gap-2 rounded-lg border px-3 text-sm">
                <input
                  type="checkbox"
                  checked={filters.include_archived}
                  onChange={(event) =>
                    update({ include_archived: event.target.checked, page: 1 })
                  }
                  className="accent-primary"
                />
                Include archived
              </label>
            ) : null}
            {hasFilters ? (
              <Button type="button" variant="ghost" onClick={clearFilters}>
                Clear filters
              </Button>
            ) : null}
          </div>

          {query.isLoading ? (
            <RegistrySkeleton columns={7} />
          ) : query.isError ? (
            <ErrorState
              title="Households could not be loaded"
              description={query.error.message}
              actionLabel="Try again"
              onAction={() => query.refetch()}
            />
          ) : items.length === 0 ? (
            <EmptyState
              title={hasFilters ? "No households match" : "No households yet"}
              description={
                hasFilters
                  ? "Adjust or clear the search and filters."
                  : "Create the first household when registry work begins."
              }
              actionLabel={hasFilters ? "Clear filters" : undefined}
              onAction={hasFilters ? clearFilters : undefined}
            />
          ) : (
            <>
              <div className="hidden overflow-x-auto md:block">
                <table className="w-full min-w-[900px] text-left text-sm">
                  <thead className="border-b text-xs uppercase tracking-wide text-muted-foreground">
                    <tr>
                      <th className="px-3 py-3">Household number</th>
                      <th className="px-3 py-3">Head</th>
                      <th className="px-3 py-3">Purok</th>
                      <th className="px-3 py-3">Address</th>
                      <th className="px-3 py-3">Members</th>
                      <th className="px-3 py-3">Status</th>
                      <th className="px-3 py-3">
                        <span className="sr-only">Actions</span>
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {items.map((item) => (
                      <tr key={item.id} className="hover:bg-muted/35">
                        <td className="px-3 py-4 font-semibold">
                          {item.household_number}
                        </td>
                        <td className="px-3 py-4">
                          {item.head_name || "Not assigned"}
                        </td>
                        <td className="px-3 py-4">{item.purok_name}</td>
                        <td className="max-w-64 truncate px-3 py-4 text-muted-foreground">
                          {item.address_line}
                        </td>
                        <td className="px-3 py-4">{item.member_count}</td>
                        <td className="px-3 py-4">
                          <StatusBadge
                            status={HOUSEHOLD_STATUS_LABELS[item.status]}
                          />
                        </td>
                        <td className="px-3 py-4">
                          <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            aria-label={`View ${item.household_number}`}
                            onClick={() => setDetailId(item.id)}
                          >
                            <Eye />
                          </Button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <div className="space-y-3 md:hidden">
                {items.map((item) => (
                  <button
                    key={item.id}
                    type="button"
                    onClick={() => setDetailId(item.id)}
                    className="w-full rounded-xl border p-4 text-left"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="font-semibold">{item.household_number}</p>
                        <p className="mt-1 text-xs text-muted-foreground">
                          {item.purok_name}
                        </p>
                      </div>
                      <StatusBadge
                        status={HOUSEHOLD_STATUS_LABELS[item.status]}
                      />
                    </div>
                    <p className="mt-3 text-sm">{item.address_line}</p>
                    <div className="mt-3 flex gap-4 text-xs text-muted-foreground">
                      <span>{item.head_name || "No head assigned"}</span>
                      <span>{item.member_count} member(s)</span>
                    </div>
                  </button>
                ))}
              </div>
              <RegistryPagination
                page={filters.page}
                pageSize={filters.page_size}
                total={query.data.total}
                onChange={update}
              />
            </>
          )}
        </CardContent>
      </Card>

      <HouseholdFormDialog
        open={form.open}
        onOpenChange={(open) => setForm((current) => ({ ...current, open }))}
        household={form.record}
        onSaved={() => setForm({ open: false, record: null })}
      />
      <HouseholdDetailDialog
        householdId={detailId}
        open={Boolean(detailId)}
        onOpenChange={(open) => {
          if (!open) setDetailId(null);
        }}
        canManage={canManage}
        canRestore={canRestore}
        onEdit={(record) => setForm({ open: true, record })}
        onArchive={(record, restoring) => setAction({ record, restoring })}
        onChanged={() => query.refetch()}
      />
      <RegistryActionDialog
        open={Boolean(action.record)}
        onOpenChange={(open) => {
          if (!open) {
            statusMutation.reset();
            setAction({ record: null, restoring: false });
          }
        }}
        kind="household"
        recordLabel={action.record?.household_number}
        restoring={action.restoring}
        pending={statusMutation.isPending}
        error={statusMutation.error}
        onConfirm={confirmStatus}
      />
      <div className="flex items-start gap-2 rounded-xl border bg-card p-4 text-xs text-muted-foreground">
        <Home className="h-4 w-4 shrink-0 text-primary" />
        Physical deletion is unavailable. Archive operations preserve
        relationships and audit history.
      </div>
    </div>
  );
}
