import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";

import { SectionHeading } from "@/components/common/SectionHeading";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  BLOOD_TYPES,
  CIVIL_STATUSES,
  PREGNANCY_STATUSES,
  PREGNANCY_STATUS_LABELS,
  RESIDENT_STATUS_LABELS,
  SEX_LABELS,
  SEX_OPTIONS,
} from "@/features/registry/constants";
import {
  useBarangays,
  useHouseholdOptions,
  usePuroks,
  useRegistryMutation,
} from "@/features/registry/hooks";
import {
  residentSchema,
  validateLocalityConsistency,
} from "@/features/registry/schemas";
import { registryService } from "@/services/registryService";

const defaults = {
  first_name: "",
  middle_name: "",
  last_name: "",
  suffix: "",
  date_of_birth: "",
  sex: "",
  civil_status: "",
  blood_type: "",
  nationality: "",
  religion: "",
  phone_number: "",
  email: "",
  occupation: "",
  barangay_id: "",
  purok_id: "",
  household_id: "",
  address_line: "",
  philhealth_number: "",
  emergency_contact_name: "",
  emergency_contact_number: "",
  emergency_contact_relationship: "",
  is_senior_citizen: false,
  is_pwd: false,
  pregnancy_status: "",
  status: "active",
};

function Field({ label, htmlFor, error, children, className = "" }) {
  return (
    <div className={`space-y-2 ${className}`}>
      <Label htmlFor={htmlFor}>{label}</Label>
      {children}
      {error ? (
        <p className="text-xs text-destructive">{error.message}</p>
      ) : null}
    </div>
  );
}

function Select({ id, register, children, disabled = false, onChange }) {
  return (
    <select
      id={id}
      {...register}
      onChange={onChange ?? register.onChange}
      disabled={disabled}
      className="flex h-10 w-full rounded-lg border border-input bg-background px-3 text-sm disabled:opacity-50"
    >
      {children}
    </select>
  );
}

export function ResidentFormDialog({ open, onOpenChange, resident, onSaved }) {
  const editing = Boolean(resident?.id);
  const [localityError, setLocalityError] = useState("");
  const barangays = useBarangays();
  const {
    register,
    handleSubmit,
    reset,
    setValue,
    watch,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(residentSchema),
    defaultValues: defaults,
  });
  const barangayId = watch("barangay_id");
  const purokId = watch("purok_id");
  const sex = watch("sex");
  const puroks = usePuroks(barangayId);
  const households = useHouseholdOptions(barangayId, purokId);
  const mutation = useRegistryMutation((values) =>
    editing
      ? registryService.updateResident(resident.id, values)
      : registryService.createResident(values),
  );

  useEffect(() => {
    if (!open) return;
    const source = resident ?? defaults;
    reset(
      Object.fromEntries(
        Object.keys(defaults).map((field) => [
          field,
          source[field] ?? defaults[field],
        ]),
      ),
    );
    setLocalityError("");
    mutation.reset();
  }, [open, resident, reset]); // eslint-disable-line react-hooks/exhaustive-deps

  async function submit(values) {
    const mismatch = validateLocalityConsistency(values, {
      puroks: puroks.data,
      households: households.data,
    });
    if (mismatch) {
      setLocalityError(mismatch);
      return;
    }
    setLocalityError("");
    await mutation.mutateAsync(values);
    toast.success(editing ? "Resident updated" : "Resident created");
    onOpenChange(false);
    onSaved?.();
  }

  return (
    <Dialog
      open={open}
      onOpenChange={mutation.isPending ? undefined : onOpenChange}
    >
      <DialogContent className="max-h-[calc(100vh-2rem)] max-w-4xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {editing ? "Edit resident" : "Add resident"}
          </DialogTitle>
          <DialogDescription>
            Resident numbers are generated by the database. Age is calculated
            from date of birth and is never stored.
          </DialogDescription>
        </DialogHeader>
        {mutation.error || localityError ? (
          <Alert variant="destructive">
            <AlertDescription>
              {localityError || mutation.error?.message}
            </AlertDescription>
          </Alert>
        ) : null}
        <form
          id="resident-form"
          className="space-y-7"
          onSubmit={handleSubmit(submit)}
          noValidate
        >
          <section className="space-y-4">
            <SectionHeading
              title="Personal information"
              description="Required identity and demographic fields"
            />
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <Field
                label="First name"
                htmlFor="resident-first"
                error={errors.first_name}
              >
                <Input id="resident-first" {...register("first_name")} />
              </Field>
              <Field
                label="Middle name"
                htmlFor="resident-middle"
                error={errors.middle_name}
              >
                <Input id="resident-middle" {...register("middle_name")} />
              </Field>
              <Field
                label="Last name"
                htmlFor="resident-last"
                error={errors.last_name}
              >
                <Input id="resident-last" {...register("last_name")} />
              </Field>
              <Field
                label="Suffix"
                htmlFor="resident-suffix"
                error={errors.suffix}
              >
                <Input id="resident-suffix" {...register("suffix")} />
              </Field>
              <Field
                label="Date of birth"
                htmlFor="resident-dob"
                error={errors.date_of_birth}
              >
                <Input
                  id="resident-dob"
                  type="date"
                  max={new Date().toISOString().slice(0, 10)}
                  {...register("date_of_birth")}
                />
              </Field>
              <Field label="Sex" htmlFor="resident-sex" error={errors.sex}>
                <Select
                  id="resident-sex"
                  register={register("sex")}
                  onChange={(event) => {
                    setValue("sex", event.target.value, {
                      shouldValidate: true,
                    });
                    if (event.target.value !== "female")
                      setValue("pregnancy_status", "", {
                        shouldValidate: true,
                      });
                  }}
                >
                  <option value="">Select sex</option>
                  {SEX_OPTIONS.map((value) => (
                    <option key={value} value={value}>
                      {SEX_LABELS[value]}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field
                label="Civil status"
                htmlFor="resident-civil"
                error={errors.civil_status}
              >
                <Select id="resident-civil" register={register("civil_status")}>
                  <option value="">Not provided</option>
                  {CIVIL_STATUSES.map((value) => (
                    <option key={value} value={value}>
                      {RESIDENT_STATUS_LABELS[value] ??
                        value[0].toUpperCase() + value.slice(1)}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field
                label="Blood type"
                htmlFor="resident-blood"
                error={errors.blood_type}
              >
                <Select id="resident-blood" register={register("blood_type")}>
                  <option value="">Not provided</option>
                  {BLOOD_TYPES.map((value) => (
                    <option key={value} value={value}>
                      {value}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field
                label="Nationality"
                htmlFor="resident-nationality"
                error={errors.nationality}
              >
                <Input id="resident-nationality" {...register("nationality")} />
              </Field>
              <Field
                label="Religion"
                htmlFor="resident-religion"
                error={errors.religion}
              >
                <Input id="resident-religion" {...register("religion")} />
              </Field>
              <Field
                label="Occupation"
                htmlFor="resident-occupation"
                error={errors.occupation}
              >
                <Input id="resident-occupation" {...register("occupation")} />
              </Field>
              <Field
                label="Status"
                htmlFor="resident-status"
                error={errors.status}
              >
                <Select id="resident-status" register={register("status")}>
                  {["active", "inactive"].map((value) => (
                    <option key={value} value={value}>
                      {RESIDENT_STATUS_LABELS[value]}
                    </option>
                  ))}
                </Select>
              </Field>
            </div>
          </section>

          <section className="space-y-4 border-t pt-6">
            <SectionHeading
              title="Locality and household"
              description="UUID-backed barangay, purok, and optional household relationships"
            />
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <Field
                label="Barangay"
                htmlFor="resident-barangay"
                error={errors.barangay_id}
              >
                <Select
                  id="resident-barangay"
                  register={register("barangay_id")}
                  onChange={(event) => {
                    setValue("barangay_id", event.target.value, {
                      shouldValidate: true,
                    });
                    setValue("purok_id", "", { shouldValidate: true });
                    setValue("household_id", "", { shouldValidate: true });
                  }}
                >
                  <option value="">Select barangay</option>
                  {(barangays.data ?? []).map((item) => (
                    <option key={item.id} value={item.id}>
                      {item.name}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field
                label="Purok"
                htmlFor="resident-purok"
                error={errors.purok_id}
              >
                <Select
                  id="resident-purok"
                  register={register("purok_id")}
                  disabled={!barangayId}
                  onChange={(event) => {
                    setValue("purok_id", event.target.value, {
                      shouldValidate: true,
                    });
                    setValue("household_id", "", { shouldValidate: true });
                  }}
                >
                  <option value="">Select purok</option>
                  {(puroks.data ?? []).map((item) => (
                    <option key={item.id} value={item.id}>
                      {item.name}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field
                label="Household"
                htmlFor="resident-household"
                error={errors.household_id}
              >
                <Select
                  id="resident-household"
                  register={register("household_id")}
                  disabled={!purokId || households.isLoading}
                >
                  <option value="">No household</option>
                  {(households.data ?? []).map((item) => (
                    <option key={item.id} value={item.id}>
                      {item.household_number} — {item.address_line}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field
                label="Address (optional)"
                htmlFor="resident-address"
                error={errors.address_line}
                className="sm:col-span-2 lg:col-span-3"
              >
                <textarea
                  id="resident-address"
                  rows={3}
                  {...register("address_line")}
                  className="flex w-full rounded-lg border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                />
              </Field>
            </div>
          </section>

          <section className="space-y-4 border-t pt-6">
            <SectionHeading title="Contact and administrative information" />
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <Field
                label="Phone number"
                htmlFor="resident-phone"
                error={errors.phone_number}
              >
                <Input
                  id="resident-phone"
                  type="tel"
                  {...register("phone_number")}
                />
              </Field>
              <Field
                label="Email"
                htmlFor="resident-email"
                error={errors.email}
              >
                <Input
                  id="resident-email"
                  type="email"
                  {...register("email")}
                />
              </Field>
              <Field
                label="PhilHealth number"
                htmlFor="resident-philhealth"
                error={errors.philhealth_number}
              >
                <Input
                  id="resident-philhealth"
                  {...register("philhealth_number")}
                />
              </Field>
            </div>
          </section>

          <section className="space-y-4 border-t pt-6">
            <SectionHeading title="Emergency contact" />
            <div className="grid gap-4 sm:grid-cols-3">
              <Field
                label="Name"
                htmlFor="emergency-name"
                error={errors.emergency_contact_name}
              >
                <Input
                  id="emergency-name"
                  {...register("emergency_contact_name")}
                />
              </Field>
              <Field
                label="Phone number"
                htmlFor="emergency-phone"
                error={errors.emergency_contact_number}
              >
                <Input
                  id="emergency-phone"
                  type="tel"
                  {...register("emergency_contact_number")}
                />
              </Field>
              <Field
                label="Relationship"
                htmlFor="emergency-relationship"
                error={errors.emergency_contact_relationship}
              >
                <Input
                  id="emergency-relationship"
                  {...register("emergency_contact_relationship")}
                />
              </Field>
            </div>
          </section>

          <section className="space-y-4 border-t pt-6">
            <SectionHeading
              title="Classification"
              description="Administrative indicators only; no clinical record is created"
            />
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <label className="flex min-h-10 items-center gap-3 rounded-lg border px-3 text-sm">
                <input
                  type="checkbox"
                  className="h-4 w-4 accent-primary"
                  {...register("is_senior_citizen")}
                />{" "}
                Senior Citizen
              </label>
              <label className="flex min-h-10 items-center gap-3 rounded-lg border px-3 text-sm">
                <input
                  type="checkbox"
                  className="h-4 w-4 accent-primary"
                  {...register("is_pwd")}
                />{" "}
                PWD
              </label>
              {sex === "female" ? (
                <Field
                  label="Pregnancy status"
                  htmlFor="resident-pregnancy"
                  error={errors.pregnancy_status}
                >
                  <Select
                    id="resident-pregnancy"
                    register={register("pregnancy_status")}
                  >
                    <option value="">Not captured</option>
                    {PREGNANCY_STATUSES.map((value) => (
                      <option key={value} value={value}>
                        {PREGNANCY_STATUS_LABELS[value]}
                      </option>
                    ))}
                  </Select>
                </Field>
              ) : null}
            </div>
          </section>
        </form>
        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={mutation.isPending}
          >
            Cancel
          </Button>
          <Button
            type="submit"
            form="resident-form"
            disabled={mutation.isPending}
          >
            {mutation.isPending ? (
              <LoaderCircle className="animate-spin" />
            ) : (
              <Save />
            )}
            {mutation.isPending ? "Saving…" : "Save resident"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
